sudo: required
dist: trusty
language: bash
before_install:
        - wget https://raw.githubusercontent.com/dokku/dokku/v0.4.6/bootstrap.sh && sudo DOKKU_TAG="v0.4.6" bash bootstrap.sh
install:
        - sudo make ci-dependencies install
        - sudo initctl reload-configuration
        - sleep 5
script:
        - make test
